# Generated by Django 2.1.13 on 2022-11-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articlepost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='column',
        ),
        migrations.DeleteModel(
            name='ArticleColumn',
        ),
    ]
